# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:05:43+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, constr


class ErrorCode(Enum):
    UK_OBIE_Field_Expected = 'UK.OBIE.Field.Expected'
    UK_OBIE_Field_Invalid = 'UK.OBIE.Field.Invalid'
    UK_OBIE_Field_InvalidDate = 'UK.OBIE.Field.InvalidDate'
    UK_OBIE_Field_Missing = 'UK.OBIE.Field.Missing'
    UK_OBIE_Field_Unexpected = 'UK.OBIE.Field.Unexpected'
    UK_OBIE_Header_Invalid = 'UK.OBIE.Header.Invalid'
    UK_OBIE_Header_Missing = 'UK.OBIE.Header.Missing'
    UK_OBIE_Resource_ConsentMismatch = 'UK.OBIE.Resource.ConsentMismatch'
    UK_OBIE_Resource_InvalidConsentStatus = 'UK.OBIE.Resource.InvalidConsentStatus'
    UK_OBIE_Resource_InvalidFormat = 'UK.OBIE.Resource.InvalidFormat'
    UK_OBIE_Resource_NotFound = 'UK.OBIE.Resource.NotFound'
    UK_OBIE_Rules_AfterCutOffDateTime = 'UK.OBIE.Rules.AfterCutOffDateTime'
    UK_OBIE_Rules_DuplicateReference = 'UK.OBIE.Rules.DuplicateReference'
    UK_OBIE_Signature_Invalid = 'UK.OBIE.Signature.Invalid'
    UK_OBIE_Signature_InvalidClaim = 'UK.OBIE.Signature.InvalidClaim'
    UK_OBIE_Signature_MissingClaim = 'UK.OBIE.Signature.MissingClaim'
    UK_OBIE_Signature_Malformed = 'UK.OBIE.Signature.Malformed'
    UK_OBIE_Signature_Missing = 'UK.OBIE.Signature.Missing'
    UK_OBIE_Signature_Unexpected = 'UK.OBIE.Signature.Unexpected'
    UK_OBIE_Unsupported_AccountIdentifier = 'UK.OBIE.Unsupported.AccountIdentifier'
    UK_OBIE_Unsupported_AccountSecondaryIdentifier = (
        'UK.OBIE.Unsupported.AccountSecondaryIdentifier'
    )
    UK_OBIE_Unsupported_Currency = 'UK.OBIE.Unsupported.Currency'
    UK_OBIE_Unsupported_EventType = 'UK.OBIE.Unsupported.EventType'
    UK_OBIE_Unsupported_Frequency = 'UK.OBIE.Unsupported.Frequency'
    UK_OBIE_Unsupported_LocalInstrument = 'UK.OBIE.Unsupported.LocalInstrument'
    UK_OBIE_Unsupported_Scheme = 'UK.OBIE.Unsupported.Scheme'
    UK_OBIE_Reauthenticate = 'UK.OBIE.Reauthenticate'
    UK_OBIE_Rules_ResourceAlreadyExists = 'UK.OBIE.Rules.ResourceAlreadyExists'
    UK_OBIE_UnexpectedError = 'UK.OBIE.UnexpectedError'


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    errorMessage: Optional[str] = None


class Links(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    First: Optional[str] = Field(None, description='')
    Last: Optional[str] = Field(None, description='')
    Next: Optional[str] = Field(None, description='')
    Prev: Optional[str] = Field(None, description='')
    Self: str = Field(..., description='')


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    FirstAvailableDateTime: Optional[str] = Field(
        None,
        description='All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    LastAvailableDateTime: Optional[str] = Field(
        None,
        description='All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    TotalPages: Optional[int] = Field(None, description='')


class OBActiveOrHistoricCurrencyAndAmount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Amount: constr(pattern=r'^\d{1,13}$|^\d{1,13}[\.,]\d{1,5}$') = Field(
        ...,
        description='A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217.',
    )
    Currency: constr(pattern=r'^[A-Z]{3,3}$') = Field(
        ...,
        description='A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".',
    )


class OBBalanceType1Code(Enum):
    ClosingAvailable = 'ClosingAvailable'
    ClosingBooked = 'ClosingBooked'
    ClosingCleared = 'ClosingCleared'
    Expected = 'Expected'
    ForwardAvailable = 'ForwardAvailable'
    Information = 'Information'
    InterimAvailable = 'InterimAvailable'
    InterimBooked = 'InterimBooked'
    InterimCleared = 'InterimCleared'
    OpeningAvailable = 'OpeningAvailable'
    OpeningBooked = 'OpeningBooked'
    OpeningCleared = 'OpeningCleared'
    PreviouslyClosedBooked = 'PreviouslyClosedBooked'


class OBBeneficiaryType1Code(Enum):
    Trusted = 'Trusted'
    Ordinary = 'Ordinary'


class OBBranchAndFinancialInstitutionIdentification5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Identification: constr(min_length=1, max_length=35) = Field(
        ...,
        description='Unique and unambiguous identification of the servicing institution.',
    )
    SchemeName: str = Field(
        ...,
        description='Name of the identification scheme, in a coded form as published in an external list.',
        examples=['[ "UK.OBIE.BICFI" ]'],
    )


class OBCashAccount5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Identification: constr(min_length=1, max_length=256) = Field(
        ...,
        description='Identification assigned by an institution to identify an account. This identification is known by the account owner.',
    )
    Name: Optional[constr(min_length=1, max_length=70)] = Field(
        None,
        description="The account name is the name or names of the account owner(s) represented at an account level, as displayed by the ASPSP's online channels.\r\nNote, the account name is not the product name or the nickname of the account.",
    )
    SchemeName: str = Field(
        ...,
        description='Name of the identification scheme, in a coded form as published in an external list.',
        examples=[
            '[ "UK.OBIE.BBAN", "UK.OBIE.IBAN", "UK.OBIE.PAN", "UK.OBIE.Paym", "UK.OBIE.SortCodeAccountNumber" ]'
        ],
    )
    SecondaryIdentification: Optional[constr(min_length=1, max_length=34)] = Field(
        None,
        description='This is secondary identification of the account, as assigned by the account servicing institution.\r\nThis can be used by building societies to additionally identify accounts with a roll number(in addition to a sort code and account number combination).',
    )


class OBCashAccount6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Identification: Optional[constr(min_length=1, max_length=256)] = Field(
        None,
        description='Identification assigned by an institution to identify an account. This identification is known by the account owner.',
    )
    Name: Optional[constr(min_length=1, max_length=70)] = Field(
        None,
        description="The account name is the name or names of the account owner(s) represented at an account level, as displayed by the ASPSP's online channels.\r\nNote, the account name is not the product name or the nickname of the account.",
    )
    SchemeName: Optional[str] = Field(
        None,
        description='Name of the identification scheme, in a coded form as published in an external list.',
        examples=[
            '[ "UK.OBIE.BBAN", "UK.OBIE.IBAN", "UK.OBIE.PAN", "UK.OBIE.Paym", "UK.OBIE.SortCodeAccountNumber" ]'
        ],
    )


class OBCreditDebitCode(Enum):
    Credit = 'Credit'
    Debit = 'Debit'


class OBEntryStatus1Code(Enum):
    Booked = 'Booked'
    Pending = 'Pending'


class OBError1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ErrorCode_1: ErrorCode = Field(..., alias='ErrorCode')
    Message: constr(min_length=1, max_length=500) = Field(
        ...,
        description="A description of the error that occurred. e.g., 'A mandatory field isn't supplied' or 'RequestedExecutionDateTime must be in future'OBIE doesn't standardise this field",
    )
    Path: Optional[constr(min_length=1, max_length=500)] = Field(
        None,
        description='Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency',
    )


class OBErrorResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Code: constr(min_length=1, max_length=40) = Field(
        ..., description='High level textual error code, to help categorize the errors.'
    )
    Errors: List[OBError1] = Field(..., description='Gets or Sets Errors')
    Id: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.',
    )
    Message: constr(min_length=1, max_length=500) = Field(
        ...,
        description="Brief Error message, e.g., 'There is something wrong with the request parameters provided'",
    )


class OBExternalAccountSubType1Code(Enum):
    ChargeCard = 'ChargeCard'
    CreditCard = 'CreditCard'
    CurrentAccount = 'CurrentAccount'
    EMoney = 'EMoney'
    Loan = 'Loan'
    Mortgage = 'Mortgage'
    PrePaidCard = 'PrePaidCard'
    Savings = 'Savings'


class OBExternalAccountType1Code(Enum):
    Business = 'Business'
    Personal = 'Personal'


class OBExternalLimitType1Code(Enum):
    Available = 'Available'
    Credit = 'Credit'
    Emergency = 'Emergency'
    Pre_Agreed = 'Pre-Agreed'
    Temporary = 'Temporary'


class OBExternalPermissions1Code(Enum):
    ReadAccountsBasic = 'ReadAccountsBasic'
    ReadAccountsDetail = 'ReadAccountsDetail'
    ReadBalances = 'ReadBalances'
    ReadBeneficiariesBasic = 'ReadBeneficiariesBasic'
    ReadBeneficiariesDetail = 'ReadBeneficiariesDetail'
    ReadDirectDebits = 'ReadDirectDebits'
    ReadOffers = 'ReadOffers'
    ReadPAN = 'ReadPAN'
    ReadParty = 'ReadParty'
    ReadPartyPSU = 'ReadPartyPSU'
    ReadProducts = 'ReadProducts'
    ReadScheduledPaymentsBasic = 'ReadScheduledPaymentsBasic'
    ReadScheduledPaymentsDetail = 'ReadScheduledPaymentsDetail'
    ReadStandingOrdersBasic = 'ReadStandingOrdersBasic'
    ReadStandingOrdersDetail = 'ReadStandingOrdersDetail'
    ReadStatementsBasic = 'ReadStatementsBasic'
    ReadStatementsDetail = 'ReadStatementsDetail'
    ReadTransactionsBasic = 'ReadTransactionsBasic'
    ReadTransactionsCredits = 'ReadTransactionsCredits'
    ReadTransactionsDebits = 'ReadTransactionsDebits'
    ReadTransactionsDetail = 'ReadTransactionsDetail'


class OBExternalRequestStatus1Code(Enum):
    Authorised = 'Authorised'
    AwaitingAuthorisation = 'AwaitingAuthorisation'
    Rejected = 'Rejected'
    Revoked = 'Revoked'


class OBExternalScheduleType1Code(Enum):
    Arrival = 'Arrival'
    Execution = 'Execution'


class OBExternalStandingOrderStatus1Code(Enum):
    Active = 'Active'
    Inactive = 'Inactive'


class OBExternalStatementType1Code(Enum):
    AccountClosure = 'AccountClosure'
    AccountOpening = 'AccountOpening'
    Annual = 'Annual'
    Interim = 'Interim'
    RegularPeriodic = 'RegularPeriodic'


class OBParty2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: Optional[constr(min_length=1, max_length=70)] = Field(
        None,
        description='Name by which a party is known and which is usually used to identify that party.',
    )
    PartyId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the customer resource. This identifier has no meaning to the account owner.',
    )


class OBReadData1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ExpirationDateTime: Optional[datetime] = Field(
        None,
        description='Specified date and time the permissions will expire. If this is not populated, the permissions will be open ended. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    Permissions: List[OBExternalPermissions1Code] = Field(
        ...,
        description='Specifies the Open Banking account access data types. This is a list of the data clusters being consented by the PSU, and requested for authorisation with the ASPSP.',
    )
    TransactionFromDateTime: Optional[datetime] = Field(
        None,
        description='Specified start date and time for the transaction query period. If this is not populated, the start date will be open ended, and data will be returned from the earliest available transaction. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    TransactionToDateTime: Optional[datetime] = Field(
        None,
        description='Specified end date and time for the transaction query period. If this is not populated, the end date will be open ended, and data will be returned to the latest available transaction. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )


class OBReadDataConsentResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ConsentId: str = Field(
        ...,
        description='Unique identification as assigned to identify the account access consent resource.',
    )
    CreationDateTime: datetime = Field(
        ...,
        description='Date and time at which the resource was created. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    ExpirationDateTime: Optional[datetime] = Field(
        None,
        description='Specified date and time the permissions will expire. If this is not populated, the permissions will be open ended. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    Permissions: List[OBExternalPermissions1Code] = Field(
        ...,
        description='Specifies the Open Banking account access data types. This is a list of the data clusters being consented by the PSU, and requested for authorisation with the ASPSP.',
    )
    Status: OBExternalRequestStatus1Code
    StatusUpdateDateTime: datetime = Field(
        ...,
        description='Date and time at which the resource status was updated. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    TransactionFromDateTime: Optional[datetime] = Field(
        None,
        description='Specified start date and time for the transaction query period. If this is not populated, the start date will be open ended, and data will be returned from the earliest available transaction. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    TransactionToDateTime: Optional[datetime] = Field(
        None,
        description='Specified end date and time for the transaction query period. If this is not populated, the end date will be open ended, and data will be returned to the latest available transaction. All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )


class OBReadDataParty2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Party: Optional[OBParty2] = None


class OBReadDataParty3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Party: Optional[List[OBParty2]] = Field(None, description='')


class OBReadParty2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataParty2
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBReadParty3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataParty3
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBRisk2(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )


class OBScheduledPayment3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    CreditorAccount: Optional[OBCashAccount5] = None
    DebtorReference: Optional[constr(min_length=1, max_length=35)] = Field(
        None,
        description='A reference value provided by the PSU to the PISP while setting up the scheduled payment.',
    )
    InstructedAmount: OBActiveOrHistoricCurrencyAndAmount
    Reference: Optional[constr(min_length=1, max_length=35)] = Field(
        None,
        description="Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction.\r\nUsage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money.\r\nIf the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor's reference or payment remittance identification should be quoted in the end-to-end transaction identification.",
    )
    ScheduledPaymentDateTime: datetime = Field(
        ...,
        description='The date on which the scheduled payment will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    ScheduledPaymentId: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='A unique and immutable identifier used to identify the scheduled payment resource. This identifier has no meaning to the account owner.',
    )
    ScheduledType: OBExternalScheduleType1Code


class OBStandingOrder5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    CreditorAccount: Optional[OBCashAccount5] = None
    FinalPaymentAmount: Optional[OBActiveOrHistoricCurrencyAndAmount] = None
    FinalPaymentDateTime: Optional[datetime] = Field(
        None,
        description='The date on which the final payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    FirstPaymentAmount: Optional[OBActiveOrHistoricCurrencyAndAmount] = None
    FirstPaymentDateTime: Optional[datetime] = Field(
        None,
        description='The date on which the first payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    Frequency: constr(
        pattern=r'^(IntrvlMnthDay:(0[1,2,3,4,6]|12|24):(0[1-9]|[12] [0-9]|3[01]))$'
    ) = Field(
        ...,
        description='Individual Definitions:\r\nIntrvlMnthDay - An interval specified in months(between 01, 02, 03, 04, 06, 12, 24), specifying the day within the month(01 to 31)\r\nFull Regular Expression:\r\n^(IntrvlMnthDay:(0[1,2,3,4,6]|12|24):(0[1-9]|[12] [0-9]|3[01]))$',
    )
    LastPaymentAmount: Optional[OBActiveOrHistoricCurrencyAndAmount] = None
    LastPaymentDateTime: Optional[datetime] = Field(
        None,
        description='The date on which the last (most recent) payment for a Standing Order schedule was made.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    NextPaymentAmount: Optional[OBActiveOrHistoricCurrencyAndAmount] = None
    NextPaymentDateTime: Optional[datetime] = Field(
        None,
        description='The date on which the next payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    Reference: Optional[constr(min_length=1, max_length=35)] = Field(
        None,
        description="Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction.\r\nUsage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money.\r\nIf the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor's reference or payment remittance identification should be quoted in the end-to-end transaction identification.",
    )
    StandingOrderId: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='A unique and immutable identifier used to identify the standing order resource. This identifier has no meaning to the account owner.',
    )
    StandingOrderStatusCode: Optional[OBExternalStandingOrderStatus1Code] = None


class OBStatement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    CreationDateTime: datetime = Field(
        ...,
        description='Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    EndDateTime: datetime = Field(
        ...,
        description='Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    StartDateTime: datetime = Field(
        ...,
        description='Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )
    StatementId: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='Unique identifier for the statement resource within an servicing institution. This identifier is both unique and immutable.',
    )
    StatementReference: Optional[constr(min_length=1, max_length=35)] = Field(
        None,
        description='Unique reference for the statement. This reference may be optionally populated if available.',
    )
    Type: OBExternalStatementType1Code


class OBTransactionCashBalance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Amount: OBActiveOrHistoricCurrencyAndAmount
    CreditDebitIndicator: OBCreditDebitCode
    Type: OBBalanceType1Code


class ProprietaryBankTransactionCodeStructure1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Code: constr(min_length=1, max_length=35) = Field(
        ...,
        description='Proprietary bank transaction code to identify the underlying transaction.',
    )
    Issuer: Optional[constr(min_length=1, max_length=35)] = Field(
        None,
        description='Identification of the issuer of the proprietary bank transaction code.',
    )


class SandboxBankAccountInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountSubType: str = Field(
        ...,
        description="Account's sub-type (ChargeCard, CreditCard, CurrentAccount ...)",
    )
    accountType: str = Field(..., description="Account's type (Business, Personal)")
    alias: Optional[constr(min_length=1, max_length=70)] = Field(
        None, description="Account's alias"
    )
    availableBalance: Optional[float] = Field(
        None, description="Account's available balance"
    )
    currency: constr(pattern=r'^[A-Z]{3,3}$') = Field(
        ..., description='Currency (EUR, USD ...)'
    )
    description: Optional[constr(min_length=1, max_length=35)] = Field(
        None, description="Account's description"
    )
    iban: str = Field(..., description="Account's IBAN")
    ledgerBalance: Optional[float] = Field(None, description="Account's ledger balance")
    openingDate: Optional[datetime] = Field(None, description="Account's opening date")
    overdraftLimit: Optional[float] = Field(
        None, description="Account's overdraft limit"
    )


class SandboxBeneficiary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = Field(None, description='Beneficiary name')


class SandboxCardInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    availableBalance: Optional[float] = Field(None, description='Available balance')
    creditLimit: Optional[float] = Field(
        None, description='Credit limit ( applicable to credit cards )'
    )
    description: Optional[str] = Field(None, description='Description')
    expiration: constr(min_length=1, max_length=7) = Field(
        ..., description='Expiration date (05/2022)'
    )
    holderName: str = Field(..., description='Holder name')
    ledgerBalance: Optional[float] = Field(None, description='Ledger balance')
    number: constr(min_length=1, max_length=16) = Field(..., description='Card number')
    subType: Optional[str] = Field(None, description='Sub type')
    type: Optional[str] = Field(None, description='Type')


class SandboxParty(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[str] = Field(None, description='Party id')
    name: Optional[str] = Field(None, description='Name')


class SandboxRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sandboxId: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Sandbox Id'
    )


class SandboxRetryCacheEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cacheKey: Optional[str] = Field(None, description='Cache key')
    count: Optional[int] = Field(None, description='Number of retries ( up to 4 )')
    expirationTimestamp: Optional[datetime] = Field(
        None, description='Expiration timestamp of the entry'
    )


class SandboxScheduledPayment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: Optional[float] = Field(None, description='Amount')
    description: Optional[constr(min_length=1, max_length=35)] = Field(
        None, description="Scheduled payment's short description"
    )
    executionDate: Optional[datetime] = Field(
        None, description="Scheduled payment's execution date"
    )
    senderReference: Optional[constr(min_length=1, max_length=35)] = Field(
        None, description='Debtor / Sender reference'
    )


class SandboxStandingOrder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: Optional[float] = Field(None, description='Standing order amount')
    description: Optional[str] = Field(
        None, description='Standing order short description'
    )
    finalPaymentDate: Optional[datetime] = Field(
        None, description='Standing order final collection date'
    )
    firstPaymentDate: Optional[datetime] = Field(
        None, description='Standing order first collection date'
    )
    frequency: constr(min_length=1, max_length=35) = Field(
        ..., description='Standing order frequency'
    )
    lastPaymentDate: Optional[datetime] = Field(
        None, description='Standing order last executed payment date'
    )
    nextPaymentDate: Optional[datetime] = Field(
        None, description='Standing order next collection date'
    )
    status: Optional[str] = Field(
        None, description='Standing order status (Active, Inactive)'
    )


class SandboxStatement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    month: Optional[int] = Field(None, description='Statement month')
    number: Optional[str] = Field(None, description='Statement number')
    year: Optional[int] = Field(None, description='Statement year')


class SandboxTransaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountingBalance: Optional[float] = Field(None, description='Balance')
    amount: Optional[float] = Field(None, description='Amount')
    bookingDateTime: Optional[datetime] = Field(None, description='Booking date time')
    creditDebit: Optional[str] = Field(None, description='Credit / Debit indicator')
    currency: Optional[str] = Field(None, description='Currency (EUR, USD ...)')
    description: Optional[str] = Field(None, description='Description')
    reference: Optional[str] = Field(None, description='Transaction reference')
    relatedAccount: Optional[str] = Field(None, description='Related account')
    relatedName: Optional[str] = Field(None, description='Related account')
    transactionCode: Optional[str] = Field(None, description='Transaction code')
    valueDateTime: Optional[datetime] = Field(None, description='Valeur')


class OBAccount6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Account: Optional[List[OBCashAccount5]] = Field(
        None, description='Provides the details to identify an account.'
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    AccountSubType: OBExternalAccountSubType1Code
    AccountType: OBExternalAccountType1Code
    Currency: constr(pattern=r'^[A-Z]{3,3}$') = Field(
        ...,
        description='Identification of the currency in which the account is held.  Usage: Currency should only be used in case one and the same account number covers several currencies and the initiating party needs to identify which currency needs to be used for settlement on the account.',
    )
    Description: Optional[constr(min_length=1, max_length=35)] = Field(
        None, description='Specifies the description of the account type.'
    )
    Nickname: Optional[constr(min_length=1, max_length=70)] = Field(
        None,
        description='The nickname of the account, assigned by the account owner in order to provide an additional means of identification of the account.',
    )
    OpeningDate: Optional[datetime] = Field(
        None,
        description='Date on which the account and related basic services are effectively operational for the account owner.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    Servicer: Optional[OBBranchAndFinancialInstitutionIdentification5] = None


class OBBeneficiary5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    BeneficiaryType: Optional[OBBeneficiaryType1Code] = None
    CreditorAccount: Optional[OBCashAccount5] = None


class OBCreditLine1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Amount: Optional[OBActiveOrHistoricCurrencyAndAmount] = None
    Included: bool = Field(
        ...,
        description='Indicates whether or not the credit line is included in the balance of the account.\r\nUsage: If not present, credit line is not included in the balance amount of the account.',
    )
    Type: Optional[OBExternalLimitType1Code] = None


class OBReadConsent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadData1
    Risk: OBRisk2


class OBReadConsentResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataConsentResponse1
    Links_1: Links = Field(..., alias='Links')
    Meta_1: Meta = Field(..., alias='Meta')
    Risk: OBRisk2


class OBReadDataAccount5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Account: Optional[List[OBAccount6]] = Field(
        None,
        description='Unambiguous identification of the account to which credit and debit entries are made.',
    )


class OBReadDataBeneficiary5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Beneficiary: Optional[List[OBBeneficiary5]] = Field(None, description='')


class OBReadDataScheduledPayment3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ScheduledPayment: Optional[List[OBScheduledPayment3]] = Field(None, description='')


class OBReadDataStandingOrder5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    StandingOrder: Optional[List[OBStandingOrder5]] = Field(None, description='')


class OBReadDataStatement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Statement: Optional[List[OBStatement2]] = Field(
        None, description='Provides further details on a statement resource.'
    )


class OBReadScheduledPayment3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataScheduledPayment3
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBReadStandingOrder6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataStandingOrder5
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBReadStatement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataStatement2
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBTransaction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    Amount: OBActiveOrHistoricCurrencyAndAmount
    Balance: Optional[OBTransactionCashBalance] = None
    BookingDateTime: datetime = Field(
        ...,
        description="Date and time when a transaction entry is posted to an account on the account servicer's books.\r\nUsage: Booking date is the expected booking date, unless the status is booked, in which case it is the actual booking date.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00",
    )
    CreditDebitIndicator: OBCreditDebitCode
    CreditorAccount: Optional[OBCashAccount6] = None
    DebtorAccount: Optional[OBCashAccount6] = None
    ProprietaryBankTransactionCode: Optional[
        ProprietaryBankTransactionCodeStructure1
    ] = None
    Status: OBEntryStatus1Code
    TransactionInformation: Optional[constr(min_length=1, max_length=500)] = Field(
        None,
        description='Further details of the transaction.\r\nThis is the transaction narrative, which is unstructured text.',
    )
    TransactionReference: Optional[constr(min_length=1, max_length=210)] = Field(
        None,
        description='Unique reference for the transaction. This reference is optionally populated, and may as an example be the FPID in the Faster Payments context.',
    )
    ValueDateTime: Optional[datetime] = Field(
        None,
        description='Date and time at which assets become available to the account owner in case of a credit entry, or cease to be available to the account owner in case of a debit transaction entry.\r\nUsage: If transaction entry status is pending and value date is present, then the value date refers to an expected/requested value date.\r\nFor transaction entries subject to availability/float and for which availability information is provided, the value date must not be used.In this case the availability component identifies the number of availability days.All dates in the JSON payloads are represented in ISO 8601 date-time format.\r\nAll date-time fields in responses must include the timezone.An example is below:\r\n2017-04-05T10:43:07+00:00',
    )


class SandboxBankAccount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    beneficiaries: Optional[List[SandboxBeneficiary]] = Field(
        None, description="List of account's beneficiaries"
    )
    info: Optional[SandboxBankAccountInfo] = None
    party: Optional[SandboxParty] = None
    scheduledPayments: Optional[List[SandboxScheduledPayment]] = Field(
        None, description="List of account's scheduled payments"
    )
    standingOrders: Optional[List[SandboxStandingOrder]] = Field(
        None, description="List of account's standing orders"
    )
    statements: Optional[List[SandboxStatement]] = Field(
        None, description="List of account's statements"
    )
    transactions: Optional[List[SandboxTransaction]] = Field(
        None, description="List of account's transactions"
    )


class SandboxCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    info: Optional[SandboxCardInfo] = None
    party: Optional[SandboxParty] = None
    statements: Optional[List[SandboxStatement]] = Field(
        None, description='Card statements'
    )
    transactions: Optional[List[SandboxTransaction]] = Field(
        None, description='Card transactions'
    )


class SandboxUser(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accounts: Optional[List[SandboxBankAccount]] = Field(
        None, description='List of accounts'
    )
    cards: Optional[List[SandboxCard]] = Field(None, description='List of cards')
    retryCacheEntries: Optional[List[SandboxRetryCacheEntry]] = Field(
        None, description='Retry cache entries'
    )
    userId: Optional[str] = Field(None, description='Connected user id')


class OBCashBalance1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    AccountId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.',
    )
    Amount: OBActiveOrHistoricCurrencyAndAmount
    CreditDebitIndicator: OBCreditDebitCode
    CreditLine: Optional[List[OBCreditLine1]] = Field(
        None, description='Set of elements used to provide details on the credit line.'
    )
    DateTime: datetime = Field(
        ...,
        description='Indicates the date (and time) of the balance.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00',
    )
    Type: OBBalanceType1Code


class OBReadAccount5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataAccount5
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBReadBeneficiary5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataBeneficiary5
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class OBReadDataBalance1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Balance: List[OBCashBalance1] = Field(
        ..., description='Set of elements used to define the balance details.'
    )


class OBReadDataTransaction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Transaction: Optional[List[OBTransaction6]] = Field(
        None, description='Provides further details on an entry in the report.'
    )


class OBReadTransaction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataTransaction6
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class Sandbox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sandboxId: constr(pattern=r'^[a-zA-Z0-9_-]+$') = Field(
        ..., description='Sandbox id'
    )
    users: Optional[List[SandboxUser]] = Field(None, description='List of users')


class OBReadBalance1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: OBReadDataBalance1
    Links_1: Links = Field(..., alias='Links')
    Meta_1: Meta = Field(..., alias='Meta')
